[project]
name = "vball"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keras==2.10.0",
    "opencv-contrib-python>=4.11.0.86",
]
